FROM golang:1.22-alpine

WORKDIR /app

# Copy the contents of the current directory to the /app directory in the image
COPY . .

# Download module dependencies
RUN go mod download

# Build the Go application
RUN go build -o /main

# Expose port 8000
EXPOSE 8000

# Specify the command to run on container start
CMD ["/main"]